name:                tiger
version:             0.1.0.0
github:              "heitor-lassarote/modern-compiler-implementation"
license:             BSD3
author:              "Heitor Toledo Lassarote de Paula"
maintainer:          "heitortoledo@hotmail.com"
copyright:           "Copyright (c) Heitor Toledo Lassarote de Paula"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/heitor-lassarote/modern-compiler-implementation#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- BlockArguments
- DerivingStrategies
- ImportQualifiedPost
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings

ghc-options:
- -Weverything
- -Wno-all-missed-specializations
- -Wno-implicit-prelude
- -Wno-missing-import-lists
- -Wno-missing-safe-haskell-mode
- -Wno-prepositive-qualified-module
- -Wno-safe
- -Wno-unsafe

library:
  source-dirs: src
  dependencies:
  - array
  - bytestring
  build-tools:
  - alex
  - happy

executables:
  tiger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies: []

tests:
  tiger-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - bytestring
    - filepath
    - tasty
    - tasty-hunit
    - tiger
